#ifndef REGIME_V1_TEST_CONSTANTS_HPP
#define REGIME_V1_TEST_CONSTANTS_HPP

const char *const BANKING_PRODUCT_V2 = "{\n"
                                       "  \"productId\": \"string\",\n"
                                       "  \"effectiveFrom\": \"string\",\n"
                                       "  \"effectiveTo\": \"string\",\n"
                                       "  \"lastUpdated\": \"string\",\n"
                                       "  \"productCategory\": \"TRANS_AND_SAVINGS_ACCOUNTS\",\n"
                                       "  \"name\": \"string\",\n"
                                       "  \"description\": \"string\",\n"
                                       "  \"brand\": \"string\",\n"
                                       "  \"brandName\": \"string\",\n"
                                       "  \"applicationUri\": \"string\",\n"
                                       "  \"isTailored\": true,\n"
                                       "  \"additionalInformation\": {\n"
                                       "    \"overviewUri\": \"string\",\n"
                                       "    \"termsUri\": \"string\",\n"
                                       "    \"eligibilityUri\": \"string\",\n"
                                       "    \"feesAndPricingUri\": \"string\",\n"
                                       "    \"bundleUri\": \"string\"\n"
                                       "  },\n"
                                       "  \"cardArt\": [\n"
                                       "    {\n"
                                       "      \"title\": \"string\",\n"
                                       "      \"imageUri\": \"string\"\n"
                                       "    }\n"
                                       "  ]\n"
                                       "}";

const char *const BANKING_PRODUCT_DETAIL = "{\n"
                                           "  \"productId\": \"string\",\n"
                                           "  \"effectiveFrom\": \"string\",\n"
                                           "  \"effectiveTo\": \"string\",\n"
                                           "  \"lastUpdated\": \"string\",\n"
                                           "  \"productCategory\": \"TRANS_AND_SAVINGS_ACCOUNTS\",\n"
                                           "  \"name\": \"string\",\n"
                                           "  \"description\": \"string\",\n"
                                           "  \"brand\": \"string\",\n"
                                           "  \"brandName\": \"string\",\n"
                                           "  \"applicationUri\": \"string\",\n"
                                           "  \"isTailored\": true,\n"
                                           "  \"additionalInformation\": {\n"
                                           "    \"overviewUri\": \"string\",\n"
                                           "    \"termsUri\": \"string\",\n"
                                           "    \"eligibilityUri\": \"string\",\n"
                                           "    \"feesAndPricingUri\": \"string\",\n"
                                           "    \"bundleUri\": \"string\"\n"
                                           "  },\n"
                                           "  \"cardArt\": [\n"
                                           "    {\n"
                                           "      \"title\": \"string\",\n"
                                           "      \"imageUri\": \"string\"\n"
                                           "    }\n"
                                           "  ],\n"
                                           "  \"bundles\": [\n"
                                           "    {\n"
                                           "      \"name\": \"string\",\n"
                                           "      \"description\": \"string\",\n"
                                           "      \"additionalInfo\": \"string\",\n"
                                           "      \"additionalInfoUri\": \"string\",\n"
                                           "      \"productIds\": [\n"
                                           "        \"string\"\n"
                                           "      ]\n"
                                           "    }\n"
                                           "  ],\n"
                                           "  \"features\": [\n"
                                           "    {\n"
                                           "      \"featureType\": \"CARD_ACCESS\",\n"
                                           "      \"additionalValue\": \"string\",\n"
                                           "      \"additionalInfo\": \"string\",\n"
                                           "      \"additionalInfoUri\": \"string\"\n"
                                           "    }\n"
                                           "  ],\n"
                                           "  \"constraints\": [\n"
                                           "    {\n"
                                           "      \"constraintType\": \"MIN_BALANCE\",\n"
                                           "      \"additionalValue\": \"string\",\n"
                                           "      \"additionalInfo\": \"string\",\n"
                                           "      \"additionalInfoUri\": \"string\"\n"
                                           "    }\n"
                                           "  ],\n"
                                           "  \"eligibility\": [\n"
                                           "    {\n"
                                           "      \"eligibilityType\": \"BUSINESS\",\n"
                                           "      \"additionalValue\": \"string\",\n"
                                           "      \"additionalInfo\": \"string\",\n"
                                           "      \"additionalInfoUri\": \"string\"\n"
                                           "    }\n"
                                           "  ],\n"
                                           "  \"fees\": [\n"
                                           "    {\n"
                                           "      \"name\": \"string\",\n"
                                           "      \"feeType\": \"PERIODIC\",\n"
                                           "      \"amount\": \"string\",\n"
                                           "      \"balanceRate\": \"string\",\n"
                                           "      \"transactionRate\": \"string\",\n"
                                           "      \"accruedRate\": \"string\",\n"
                                           "      \"accrualFrequency\": \"string\",\n"
                                           "      \"currency\": \"string\",\n"
                                           "      \"additionalValue\": \"string\",\n"
                                           "      \"additionalInfo\": \"string\",\n"
                                           "      \"additionalInfoUri\": \"string\",\n"
                                           "      \"discounts\": [\n"
                                           "        {\n"
                                           "          \"description\": \"string\",\n"
                                           "          \"discountType\": \"BALANCE\",\n"
                                           "          \"amount\": \"string\",\n"
                                           "          \"balanceRate\": \"string\",\n"
                                           "          \"transactionRate\": \"string\",\n"
                                           "          \"accruedRate\": \"string\",\n"
                                           "          \"feeRate\": \"string\",\n"
                                           "          \"additionalValue\": \"string\",\n"
                                           "          \"additionalInfo\": \"string\",\n"
                                           "          \"additionalInfoUri\": \"string\",\n"
                                           "          \"eligibility\": [\n"
                                           "            {\n"
                                           "              \"discountEligibilityType\": \"BUSINESS\",\n"
                                           "              \"additionalValue\": \"string\",\n"
                                           "              \"additionalInfo\": \"string\",\n"
                                           "              \"additionalInfoUri\": \"string\"\n"
                                           "            }\n"
                                           "          ]\n"
                                           "        }\n"
                                           "      ]\n"
                                           "    }\n"
                                           "  ],\n"
                                           "  \"depositRates\": [\n"
                                           "    {\n"
                                           "      \"depositRateType\": \"FIXED\",\n"
                                           "      \"rate\": \"string\",\n"
                                           "      \"calculationFrequency\": \"string\",\n"
                                           "      \"applicationFrequency\": \"string\",\n"
                                           "      \"tiers\": [\n"
                                           "        {\n"
                                           "          \"name\": \"string\",\n"
                                           "          \"unitOfMeasure\": \"DOLLAR\",\n"
                                           "          \"minimumValue\": 0,\n"
                                           "          \"maximumValue\": 0,\n"
                                           "          \"rateApplicationMethod\": \"WHOLE_BALANCE\",\n"
                                           "          \"applicabilityConditions\": {\n"
                                           "            \"additionalInfo\": \"string\",\n"
                                           "            \"additionalInfoUri\": \"string\"\n"
                                           "          },\n"
                                           "          \"subTier\": {\n"
                                           "            \"name\": \"string\",\n"
                                           "            \"unitOfMeasure\": \"DOLLAR\",\n"
                                           "            \"minimumValue\": 0,\n"
                                           "            \"maximumValue\": 0,\n"
                                           "            \"rateApplicationMethod\": \"WHOLE_BALANCE\",\n"
                                           "            \"applicabilityConditions\": {\n"
                                           "              \"additionalInfo\": \"string\",\n"
                                           "              \"additionalInfoUri\": \"string\"\n"
                                           "            }\n"
                                           "          }\n"
                                           "        }\n"
                                           "      ],\n"
                                           "      \"additionalValue\": \"string\",\n"
                                           "      \"additionalInfo\": \"string\",\n"
                                           "      \"additionalInfoUri\": \"string\"\n"
                                           "    }\n"
                                           "  ],\n"
                                           "  \"lendingRates\": [\n"
                                           "    {\n"
                                           "      \"lendingRateType\": \"FIXED\",\n"
                                           "      \"rate\": \"string\",\n"
                                           "      \"comparisonRate\": \"string\",\n"
                                           "      \"calculationFrequency\": \"string\",\n"
                                           "      \"applicationFrequency\": \"string\",\n"
                                           "      \"interestPaymentDue\": \"IN_ARREARS\",\n"
                                           "      \"tiers\": [\n"
                                           "        {\n"
                                           "          \"name\": \"string\",\n"
                                           "          \"unitOfMeasure\": \"DOLLAR\",\n"
                                           "          \"minimumValue\": 0,\n"
                                           "          \"maximumValue\": 0,\n"
                                           "          \"rateApplicationMethod\": \"WHOLE_BALANCE\",\n"
                                           "          \"applicabilityConditions\": {\n"
                                           "            \"additionalInfo\": \"string\",\n"
                                           "            \"additionalInfoUri\": \"string\"\n"
                                           "          },\n"
                                           "          \"subTier\": {\n"
                                           "            \"name\": \"string\",\n"
                                           "            \"unitOfMeasure\": \"DOLLAR\",\n"
                                           "            \"minimumValue\": 0,\n"
                                           "            \"maximumValue\": 0,\n"
                                           "            \"rateApplicationMethod\": \"WHOLE_BALANCE\",\n"
                                           "            \"applicabilityConditions\": {\n"
                                           "              \"additionalInfo\": \"string\",\n"
                                           "              \"additionalInfoUri\": \"string\"\n"
                                           "            }\n"
                                           "          }\n"
                                           "        }\n"
                                           "      ],\n"
                                           "      \"additionalValue\": \"string\",\n"
                                           "      \"additionalInfo\": \"string\",\n"
                                           "      \"additionalInfoUri\": \"string\"\n"
                                           "    }\n"
                                           "  ]\n"
                                           "}";

const char *const BANKING_PRODUCT_BUNDLE = "{\n"
                                           "  \"name\": \"string\",\n"
                                           "  \"description\": \"string\",\n"
                                           "  \"additionalInfo\": \"string\",\n"
                                           "  \"additionalInfoUri\": \"string\",\n"
                                           "  \"productIds\": [\n"
                                           "    \"string\"\n"
                                           "  ]\n"
                                           "}";

const char *const BANKING_PRODUCT_FEATURE = "{\n"
                                            "  \"featureType\": \"CARD_ACCESS\",\n"
                                            "  \"additionalValue\": \"string\",\n"
                                            "  \"additionalInfo\": \"string\",\n"
                                            "  \"additionalInfoUri\": \"string\"\n"
                                            "}";

const char *const BANKING_PRODUCT_CONSTRAINT = "{\n"
                                               "  \"constraintType\": \"MIN_BALANCE\",\n"
                                               "  \"additionalValue\": \"string\",\n"
                                               "  \"additionalInfo\": \"string\",\n"
                                               "  \"additionalInfoUri\": \"string\"\n"
                                               "}";

const char *const BANKING_PRODUCT_ELIGIBILITY = "{\n"
                                                "  \"eligibilityType\": \"BUSINESS\",\n"
                                                "  \"additionalValue\": \"string\",\n"
                                                "  \"additionalInfo\": \"string\",\n"
                                                "  \"additionalInfoUri\": \"string\"\n"
                                                "}";

const char *const BANKING_PRODUCT_FEE = "{\n"
                                        "  \"name\": \"string\",\n"
                                        "  \"feeType\": \"PERIODIC\",\n"
                                        "  \"amount\": \"string\",\n"
                                        "  \"balanceRate\": \"string\",\n"
                                        "  \"transactionRate\": \"string\",\n"
                                        "  \"accruedRate\": \"string\",\n"
                                        "  \"accrualFrequency\": \"string\",\n"
                                        "  \"currency\": \"string\",\n"
                                        "  \"additionalValue\": \"string\",\n"
                                        "  \"additionalInfo\": \"string\",\n"
                                        "  \"additionalInfoUri\": \"string\",\n"
                                        "  \"discounts\": [\n"
                                        "    {\n"
                                        "      \"description\": \"string\",\n"
                                        "      \"discountType\": \"BALANCE\",\n"
                                        "      \"amount\": \"string\",\n"
                                        "      \"balanceRate\": \"string\",\n"
                                        "      \"transactionRate\": \"string\",\n"
                                        "      \"accruedRate\": \"string\",\n"
                                        "      \"feeRate\": \"string\",\n"
                                        "      \"additionalValue\": \"string\",\n"
                                        "      \"additionalInfo\": \"string\",\n"
                                        "      \"additionalInfoUri\": \"string\",\n"
                                        "      \"eligibility\": [\n"
                                        "        {\n"
                                        "          \"discountEligibilityType\": \"BUSINESS\",\n"
                                        "          \"additionalValue\": \"string\",\n"
                                        "          \"additionalInfo\": \"string\",\n"
                                        "          \"additionalInfoUri\": \"string\"\n"
                                        "        }\n"
                                        "      ]\n"
                                        "    }\n"
                                        "  ]\n"
                                        "}";

const char *const BANKING_PRODUCT_DISCOUNT = "{\n"
                                             "  \"description\": \"string\",\n"
                                             "  \"discountType\": \"BALANCE\",\n"
                                             "  \"amount\": \"string\",\n"
                                             "  \"balanceRate\": \"string\",\n"
                                             "  \"transactionRate\": \"string\",\n"
                                             "  \"accruedRate\": \"string\",\n"
                                             "  \"feeRate\": \"string\",\n"
                                             "  \"additionalValue\": \"string\",\n"
                                             "  \"additionalInfo\": \"string\",\n"
                                             "  \"additionalInfoUri\": \"string\",\n"
                                             "  \"eligibility\": [\n"
                                             "    {\n"
                                             "      \"discountEligibilityType\": \"BUSINESS\",\n"
                                             "      \"additionalValue\": \"string\",\n"
                                             "      \"additionalInfo\": \"string\",\n"
                                             "      \"additionalInfoUri\": \"string\"\n"
                                             "    }\n"
                                             "  ]\n"
                                             "}";

const char *const BANKING_PRODUCT_DISCOUNT_ELIGIBILITY = "{\n"
                                                         "  \"discountEligibilityType\": \"BUSINESS\",\n"
                                                         "  \"additionalValue\": \"string\",\n"
                                                         "  \"additionalInfo\": \"string\",\n"
                                                         "  \"additionalInfoUri\": \"string\"\n"
                                                         "}";

const char *const BANKING_PRODUCT_DEPOSIT_RATE = "{\n"
                                                 "  \"depositRateType\": \"FIXED\",\n"
                                                 "  \"rate\": \"string\",\n"
                                                 "  \"calculationFrequency\": \"string\",\n"
                                                 "  \"applicationFrequency\": \"string\",\n"
                                                 "  \"tiers\": [\n"
                                                 "    {\n"
                                                 "      \"name\": \"string\",\n"
                                                 "      \"unitOfMeasure\": \"DOLLAR\",\n"
                                                 "      \"minimumValue\": 0,\n"
                                                 "      \"maximumValue\": 0,\n"
                                                 "      \"rateApplicationMethod\": \"WHOLE_BALANCE\",\n"
                                                 "      \"applicabilityConditions\": {\n"
                                                 "        \"additionalInfo\": \"string\",\n"
                                                 "        \"additionalInfoUri\": \"string\"\n"
                                                 "      },\n"
                                                 "      \"subTier\": {\n"
                                                 "        \"name\": \"string\",\n"
                                                 "        \"unitOfMeasure\": \"DOLLAR\",\n"
                                                 "        \"minimumValue\": 0,\n"
                                                 "        \"maximumValue\": 0,\n"
                                                 "        \"rateApplicationMethod\": \"WHOLE_BALANCE\",\n"
                                                 "        \"applicabilityConditions\": {\n"
                                                 "          \"additionalInfo\": \"string\",\n"
                                                 "          \"additionalInfoUri\": \"string\"\n"
                                                 "        }\n"
                                                 "      }\n"
                                                 "    }\n"
                                                 "  ],\n"
                                                 "  \"additionalValue\": \"string\",\n"
                                                 "  \"additionalInfo\": \"string\",\n"
                                                 "  \"additionalInfoUri\": \"string\"\n"
                                                 "}";

const char *const BANKING_PRODUCT_LENDING_RATE = "{\n"
                                                 "  \"lendingRateType\": \"FIXED\",\n"
                                                 "  \"rate\": \"string\",\n"
                                                 "  \"comparisonRate\": \"string\",\n"
                                                 "  \"calculationFrequency\": \"string\",\n"
                                                 "  \"applicationFrequency\": \"string\",\n"
                                                 "  \"interestPaymentDue\": \"IN_ARREARS\",\n"
                                                 "  \"tiers\": [\n"
                                                 "    {\n"
                                                 "      \"name\": \"string\",\n"
                                                 "      \"unitOfMeasure\": \"DOLLAR\",\n"
                                                 "      \"minimumValue\": 0,\n"
                                                 "      \"maximumValue\": 0,\n"
                                                 "      \"rateApplicationMethod\": \"WHOLE_BALANCE\",\n"
                                                 "      \"applicabilityConditions\": {\n"
                                                 "        \"additionalInfo\": \"string\",\n"
                                                 "        \"additionalInfoUri\": \"string\"\n"
                                                 "      },\n"
                                                 "      \"subTier\": {\n"
                                                 "        \"name\": \"string\",\n"
                                                 "        \"unitOfMeasure\": \"DOLLAR\",\n"
                                                 "        \"minimumValue\": 0,\n"
                                                 "        \"maximumValue\": 0,\n"
                                                 "        \"rateApplicationMethod\": \"WHOLE_BALANCE\",\n"
                                                 "        \"applicabilityConditions\": {\n"
                                                 "          \"additionalInfo\": \"string\",\n"
                                                 "          \"additionalInfoUri\": \"string\"\n"
                                                 "        }\n"
                                                 "      }\n"
                                                 "    }\n"
                                                 "  ],\n"
                                                 "  \"additionalValue\": \"string\",\n"
                                                 "  \"additionalInfo\": \"string\",\n"
                                                 "  \"additionalInfoUri\": \"string\"\n"
                                                 "}";

const char *const BANKING_PRODUCT_RATE_TIER = "{\n"
                                              "  \"name\": \"string\",\n"
                                              "  \"unitOfMeasure\": \"DOLLAR\",\n"
                                              "  \"minimumValue\": 0,\n"
                                              "  \"maximumValue\": 0,\n"
                                              "  \"rateApplicationMethod\": \"WHOLE_BALANCE\",\n"
                                              "  \"applicabilityConditions\": {\n"
                                              "    \"additionalInfo\": \"string\",\n"
                                              "    \"additionalInfoUri\": \"string\"\n"
                                              "  },\n"
                                              "  \"subTier\": {\n"
                                              "    \"name\": \"string\",\n"
                                              "    \"unitOfMeasure\": \"DOLLAR\",\n"
                                              "    \"minimumValue\": 0,\n"
                                              "    \"maximumValue\": 0,\n"
                                              "    \"rateApplicationMethod\": \"WHOLE_BALANCE\",\n"
                                              "    \"applicabilityConditions\": {\n"
                                              "      \"additionalInfo\": \"string\",\n"
                                              "      \"additionalInfoUri\": \"string\"\n"
                                              "    }\n"
                                              "  }\n"
                                              "}";

const char *const BANKING_PRODUCT_RATE_CONDITION = "{\n"
                                                   "  \"additionalInfo\": \"string\",\n"
                                                   "  \"additionalInfoUri\": \"string\"\n"
                                                   "}";

const char *const BANKING_ACCOUNT = "{\n"
                                    "  \"accountId\": \"string\",\n"
                                    "  \"creationDate\": \"string\",\n"
                                    "  \"displayName\": \"string\",\n"
                                    "  \"nickname\": \"string\",\n"
                                    "  \"openStatus\": \"OPEN\",\n"
                                    "  \"isOwned\": true,\n"
                                    "  \"maskedNumber\": \"string\",\n"
                                    "  \"productCategory\": \"TRANS_AND_SAVINGS_ACCOUNTS\",\n"
                                    "  \"productName\": \"string\"\n"
                                    "}";

const char *const BANKING_ACCOUNT_DETAIL = "{\n"
                                           "  \"accountId\": \"string\",\n"
                                           "  \"creationDate\": \"string\",\n"
                                           "  \"displayName\": \"string\",\n"
                                           "  \"nickname\": \"string\",\n"
                                           "  \"openStatus\": \"OPEN\",\n"
                                           "  \"isOwned\": true,\n"
                                           "  \"maskedNumber\": \"string\",\n"
                                           "  \"productCategory\": \"TRANS_AND_SAVINGS_ACCOUNTS\",\n"
                                           "  \"productName\": \"string\",\n"
                                           "  \"bsb\": \"string\",\n"
                                           "  \"accountNumber\": \"string\",\n"
                                           "  \"bundleName\": \"string\",\n"
                                           "  \"specificAccountUType\": \"termDeposit\",\n"
                                           "  \"termDeposit\": [\n"
                                           "    {\n"
                                           "      \"lodgementDate\": \"string\",\n"
                                           "      \"maturityDate\": \"string\",\n"
                                           "      \"maturityAmount\": \"string\",\n"
                                           "      \"maturityCurrency\": \"string\",\n"
                                           "      \"maturityInstructions\": \"ROLLED_OVER\"\n"
                                           "    }\n"
                                           "  ],\n"
                                           "  \"creditCard\": {\n"
                                           "    \"minPaymentAmount\": \"string\",\n"
                                           "    \"paymentDueAmount\": \"string\",\n"
                                           "    \"paymentCurrency\": \"string\",\n"
                                           "    \"paymentDueDate\": \"string\"\n"
                                           "  },\n"
                                           "  \"loan\": {\n"
                                           "    \"originalStartDate\": \"string\",\n"
                                           "    \"originalLoanAmount\": \"string\",\n"
                                           "    \"originalLoanCurrency\": \"string\",\n"
                                           "    \"loanEndDate\": \"string\",\n"
                                           "    \"nextInstalmentDate\": \"string\",\n"
                                           "    \"minInstalmentAmount\": \"string\",\n"
                                           "    \"minInstalmentCurrency\": \"string\",\n"
                                           "    \"maxRedraw\": \"string\",\n"
                                           "    \"maxRedrawCurrency\": \"string\",\n"
                                           "    \"minRedraw\": \"string\",\n"
                                           "    \"minRedrawCurrency\": \"string\",\n"
                                           "    \"offsetAccountEnabled\": true,\n"
                                           "    \"offsetAccountIds\": [\n"
                                           "      \"string\"\n"
                                           "    ],\n"
                                           "    \"repaymentType\": \"PRINCIPAL_AND_INTEREST\",\n"
                                           "    \"repaymentFrequency\": \"string\"\n"
                                           "  },\n"
                                           "  \"depositRate\": \"string\",\n"
                                           "  \"lendingRate\": \"string\",\n"
                                           "  \"depositRates\": [\n"
                                           "    {\n"
                                           "      \"depositRateType\": \"FIXED\",\n"
                                           "      \"rate\": \"string\",\n"
                                           "      \"calculationFrequency\": \"string\",\n"
                                           "      \"applicationFrequency\": \"string\",\n"
                                           "      \"tiers\": [\n"
                                           "        {\n"
                                           "          \"name\": \"string\",\n"
                                           "          \"unitOfMeasure\": \"DOLLAR\",\n"
                                           "          \"minimumValue\": 0,\n"
                                           "          \"maximumValue\": 0,\n"
                                           "          \"rateApplicationMethod\": \"WHOLE_BALANCE\",\n"
                                           "          \"applicabilityConditions\": {\n"
                                           "            \"additionalInfo\": \"string\",\n"
                                           "            \"additionalInfoUri\": \"string\"\n"
                                           "          },\n"
                                           "          \"subTier\": {\n"
                                           "            \"name\": \"string\",\n"
                                           "            \"unitOfMeasure\": \"DOLLAR\",\n"
                                           "            \"minimumValue\": 0,\n"
                                           "            \"maximumValue\": 0,\n"
                                           "            \"rateApplicationMethod\": \"WHOLE_BALANCE\",\n"
                                           "            \"applicabilityConditions\": {\n"
                                           "              \"additionalInfo\": \"string\",\n"
                                           "              \"additionalInfoUri\": \"string\"\n"
                                           "            }\n"
                                           "          }\n"
                                           "        }\n"
                                           "      ],\n"
                                           "      \"additionalValue\": \"string\",\n"
                                           "      \"additionalInfo\": \"string\",\n"
                                           "      \"additionalInfoUri\": \"string\"\n"
                                           "    }\n"
                                           "  ],\n"
                                           "  \"lendingRates\": [\n"
                                           "    {\n"
                                           "      \"lendingRateType\": \"FIXED\",\n"
                                           "      \"rate\": \"string\",\n"
                                           "      \"comparisonRate\": \"string\",\n"
                                           "      \"calculationFrequency\": \"string\",\n"
                                           "      \"applicationFrequency\": \"string\",\n"
                                           "      \"interestPaymentDue\": \"IN_ARREARS\",\n"
                                           "      \"tiers\": [\n"
                                           "        {\n"
                                           "          \"name\": \"string\",\n"
                                           "          \"unitOfMeasure\": \"DOLLAR\",\n"
                                           "          \"minimumValue\": 0,\n"
                                           "          \"maximumValue\": 0,\n"
                                           "          \"rateApplicationMethod\": \"WHOLE_BALANCE\",\n"
                                           "          \"applicabilityConditions\": {\n"
                                           "            \"additionalInfo\": \"string\",\n"
                                           "            \"additionalInfoUri\": \"string\"\n"
                                           "          },\n"
                                           "          \"subTier\": {\n"
                                           "            \"name\": \"string\",\n"
                                           "            \"unitOfMeasure\": \"DOLLAR\",\n"
                                           "            \"minimumValue\": 0,\n"
                                           "            \"maximumValue\": 0,\n"
                                           "            \"rateApplicationMethod\": \"WHOLE_BALANCE\",\n"
                                           "            \"applicabilityConditions\": {\n"
                                           "              \"additionalInfo\": \"string\",\n"
                                           "              \"additionalInfoUri\": \"string\"\n"
                                           "            }\n"
                                           "          }\n"
                                           "        }\n"
                                           "      ],\n"
                                           "      \"additionalValue\": \"string\",\n"
                                           "      \"additionalInfo\": \"string\",\n"
                                           "      \"additionalInfoUri\": \"string\"\n"
                                           "    }\n"
                                           "  ],\n"
                                           "  \"features\": [\n"
                                           "    {\n"
                                           "      \"featureType\": \"CARD_ACCESS\",\n"
                                           "      \"additionalValue\": \"string\",\n"
                                           "      \"additionalInfo\": \"string\",\n"
                                           "      \"additionalInfoUri\": \"string\",\n"
                                           "      \"isActivated\": true\n"
                                           "    }\n"
                                           "  ],\n"
                                           "  \"fees\": [\n"
                                           "    {\n"
                                           "      \"name\": \"string\",\n"
                                           "      \"feeType\": \"PERIODIC\",\n"
                                           "      \"amount\": \"string\",\n"
                                           "      \"balanceRate\": \"string\",\n"
                                           "      \"transactionRate\": \"string\",\n"
                                           "      \"accruedRate\": \"string\",\n"
                                           "      \"accrualFrequency\": \"string\",\n"
                                           "      \"currency\": \"string\",\n"
                                           "      \"additionalValue\": \"string\",\n"
                                           "      \"additionalInfo\": \"string\",\n"
                                           "      \"additionalInfoUri\": \"string\",\n"
                                           "      \"discounts\": [\n"
                                           "        {\n"
                                           "          \"description\": \"string\",\n"
                                           "          \"discountType\": \"BALANCE\",\n"
                                           "          \"amount\": \"string\",\n"
                                           "          \"balanceRate\": \"string\",\n"
                                           "          \"transactionRate\": \"string\",\n"
                                           "          \"accruedRate\": \"string\",\n"
                                           "          \"feeRate\": \"string\",\n"
                                           "          \"additionalValue\": \"string\",\n"
                                           "          \"additionalInfo\": \"string\",\n"
                                           "          \"additionalInfoUri\": \"string\",\n"
                                           "          \"eligibility\": [\n"
                                           "            {\n"
                                           "              \"discountEligibilityType\": \"BUSINESS\",\n"
                                           "              \"additionalValue\": \"string\",\n"
                                           "              \"additionalInfo\": \"string\",\n"
                                           "              \"additionalInfoUri\": \"string\"\n"
                                           "            }\n"
                                           "          ]\n"
                                           "        }\n"
                                           "      ]\n"
                                           "    }\n"
                                           "  ],\n"
                                           "  \"addresses\": [\n"
                                           "    {\n"
                                           "      \"addressUType\": \"simple\",\n"
                                           "      \"simple\": {\n"
                                           "        \"mailingName\": \"string\",\n"
                                           "        \"addressLine1\": \"string\",\n"
                                           "        \"addressLine2\": \"string\",\n"
                                           "        \"addressLine3\": \"string\",\n"
                                           "        \"postcode\": \"string\",\n"
                                           "        \"city\": \"string\",\n"
                                           "        \"state\": \"string\",\n"
                                           "        \"country\": \"AUS\"\n"
                                           "      },\n"
                                           "      \"paf\": {\n"
                                           "        \"dpid\": \"string\",\n"
                                           "        \"thoroughfareNumber1\": 0,\n"
                                           "        \"thoroughfareNumber1Suffix\": \"string\",\n"
                                           "        \"thoroughfareNumber2\": 0,\n"
                                           "        \"thoroughfareNumber2Suffix\": \"string\",\n"
                                           "        \"flatUnitType\": \"string\",\n"
                                           "        \"flatUnitNumber\": \"string\",\n"
                                           "        \"floorLevelType\": \"string\",\n"
                                           "        \"floorLevelNumber\": \"string\",\n"
                                           "        \"lotNumber\": \"string\",\n"
                                           "        \"buildingName1\": \"string\",\n"
                                           "        \"buildingName2\": \"string\",\n"
                                           "        \"streetName\": \"string\",\n"
                                           "        \"streetType\": \"string\",\n"
                                           "        \"streetSuffix\": \"string\",\n"
                                           "        \"postalDeliveryType\": \"string\",\n"
                                           "        \"postalDeliveryNumber\": 0,\n"
                                           "        \"postalDeliveryNumberPrefix\": \"string\",\n"
                                           "        \"postalDeliveryNumberSuffix\": \"string\",\n"
                                           "        \"localityName\": \"string\",\n"
                                           "        \"postcode\": \"string\",\n"
                                           "        \"state\": \"string\"\n"
                                           "      }\n"
                                           "    }\n"
                                           "  ]\n"
                                           "}";

const char *const BANKING_TERM_DEPOSIT_ACCOUNT = "{\n"
                                                 "  \"lodgementDate\": \"string\",\n"
                                                 "  \"maturityDate\": \"string\",\n"
                                                 "  \"maturityAmount\": \"string\",\n"
                                                 "  \"maturityCurrency\": \"string\",\n"
                                                 "  \"maturityInstructions\": \"ROLLED_OVER\"\n"
                                                 "}";

const char *const BANKING_CREDIT_CARD_ACCOUNT = "{\n"
                                                "  \"minPaymentAmount\": \"string\",\n"
                                                "  \"paymentDueAmount\": \"string\",\n"
                                                "  \"paymentCurrency\": \"string\",\n"
                                                "  \"paymentDueDate\": \"string\"\n"
                                                "}";

const char *const BANKING_LOAN_ACCOUNT = "{\n"
                                         "  \"originalStartDate\": \"string\",\n"
                                         "  \"originalLoanAmount\": \"string\",\n"
                                         "  \"originalLoanCurrency\": \"string\",\n"
                                         "  \"loanEndDate\": \"string\",\n"
                                         "  \"nextInstalmentDate\": \"string\",\n"
                                         "  \"minInstalmentAmount\": \"string\",\n"
                                         "  \"minInstalmentCurrency\": \"string\",\n"
                                         "  \"maxRedraw\": \"string\",\n"
                                         "  \"maxRedrawCurrency\": \"string\",\n"
                                         "  \"minRedraw\": \"string\",\n"
                                         "  \"minRedrawCurrency\": \"string\",\n"
                                         "  \"offsetAccountEnabled\": true,\n"
                                         "  \"offsetAccountIds\": [\n"
                                         "    \"string\"\n"
                                         "  ],\n"
                                         "  \"repaymentType\": \"PRINCIPAL_AND_INTEREST\",\n"
                                         "  \"repaymentFrequency\": \"string\"\n"
                                         "}";

const char *const BANKING_TRANSACTION = "\n"
                                        "\n"
                                        "{\n"
                                        "  \"accountId\": \"string\",\n"
                                        "  \"transactionId\": \"string\",\n"
                                        "  \"isDetailAvailable\": true,\n"
                                        "  \"type\": \"FEE\",\n"
                                        "  \"status\": \"PENDING\",\n"
                                        "  \"description\": \"string\",\n"
                                        "  \"postingDateTime\": \"string\",\n"
                                        "  \"valueDateTime\": \"string\",\n"
                                        "  \"executionDateTime\": \"string\",\n"
                                        "  \"amount\": \"string\",\n"
                                        "  \"currency\": \"string\",\n"
                                        "  \"reference\": \"string\",\n"
                                        "  \"merchantName\": \"string\",\n"
                                        "  \"merchantCategoryCode\": \"string\",\n"
                                        "  \"billerCode\": \"string\",\n"
                                        "  \"billerName\": \"string\",\n"
                                        "  \"crn\": \"string\",\n"
                                        "  \"apcaNumber\": \"string\"\n"
                                        "}\n"
                                        "";

const char *const BANKING_TRANSACTION_DETAIL = "{\n"
                                               "  \"accountId\": \"string\",\n"
                                               "  \"transactionId\": \"string\",\n"
                                               "  \"isDetailAvailable\": true,\n"
                                               "  \"type\": \"FEE\",\n"
                                               "  \"status\": \"PENDING\",\n"
                                               "  \"description\": \"string\",\n"
                                               "  \"postingDateTime\": \"string\",\n"
                                               "  \"valueDateTime\": \"string\",\n"
                                               "  \"executionDateTime\": \"string\",\n"
                                               "  \"amount\": \"string\",\n"
                                               "  \"currency\": \"string\",\n"
                                               "  \"reference\": \"string\",\n"
                                               "  \"merchantName\": \"string\",\n"
                                               "  \"merchantCategoryCode\": \"string\",\n"
                                               "  \"billerCode\": \"string\",\n"
                                               "  \"billerName\": \"string\",\n"
                                               "  \"crn\": \"string\",\n"
                                               "  \"apcaNumber\": \"string\",\n"
                                               "  \"extendedData\": {\n"
                                               "    \"payer\": \"string\",\n"
                                               "    \"payee\": \"string\",\n"
                                               "    \"extensionUType\": \"x2p101Payload\",\n"
                                               "    \"x2p101Payload\": {\n"
                                               "      \"extendedDescription\": \"string\",\n"
                                               "      \"endToEndId\": \"string\",\n"
                                               "      \"purposeCode\": \"string\"\n"
                                               "    },\n"
                                               "    \"service\": \"X2P1.01\"\n"
                                               "  }\n"
                                               "}";

const char *const BANKING_BALANCE = "\n"
                                    "\n"
                                    "{\n"
                                    "  \"accountId\": \"string\",\n"
                                    "  \"currentBalance\": \"string\",\n"
                                    "  \"availableBalance\": \"string\",\n"
                                    "  \"creditLimit\": \"string\",\n"
                                    "  \"amortisedLimit\": \"string\",\n"
                                    "  \"currency\": \"string\",\n"
                                    "  \"purses\": [\n"
                                    "    {\n"
                                    "      \"amount\": \"string\",\n"
                                    "      \"currency\": \"string\"\n"
                                    "    }\n"
                                    "  ]\n"
                                    "}";

const char *const BANKING_BALANCE_PURSE = "{\n"
                                          "  \"amount\": \"string\",\n"
                                          "  \"currency\": \"string\"\n"
                                          "}";

const char *const BANKING_PAYEE = "{\n"
                                  "  \"payeeId\": \"string\",\n"
                                  "  \"nickname\": \"string\",\n"
                                  "  \"description\": \"string\",\n"
                                  "  \"type\": \"DOMESTIC\",\n"
                                  "  \"creationDate\": \"string\"\n"
                                  "}";

const char *const BANKING_PAYEE_DETAIL = "{\n"
                                         "  \"payeeId\": \"string\",\n"
                                         "  \"nickname\": \"string\",\n"
                                         "  \"description\": \"string\",\n"
                                         "  \"type\": \"DOMESTIC\",\n"
                                         "  \"creationDate\": \"string\",\n"
                                         "  \"payeeUType\": \"domestic\",\n"
                                         "  \"domestic\": {\n"
                                         "    \"payeeAccountUType\": \"account\",\n"
                                         "    \"account\": {\n"
                                         "      \"accountName\": \"string\",\n"
                                         "      \"bsb\": \"string\",\n"
                                         "      \"accountNumber\": \"string\"\n"
                                         "    },\n"
                                         "    \"card\": {\n"
                                         "      \"cardNumber\": \"string\"\n"
                                         "    },\n"
                                         "    \"payId\": {\n"
                                         "      \"name\": \"string\",\n"
                                         "      \"identifier\": \"string\",\n"
                                         "      \"type\": \"EMAIL\"\n"
                                         "    }\n"
                                         "  },\n"
                                         "  \"biller\": {\n"
                                         "    \"billerCode\": \"string\",\n"
                                         "    \"crn\": \"string\",\n"
                                         "    \"billerName\": \"string\"\n"
                                         "  },\n"
                                         "  \"international\": {\n"
                                         "    \"beneficiaryDetails\": {\n"
                                         "      \"name\": \"string\",\n"
                                         "      \"country\": \"string\",\n"
                                         "      \"message\": \"string\"\n"
                                         "    },\n"
                                         "    \"bankDetails\": {\n"
                                         "      \"country\": \"string\",\n"
                                         "      \"accountNumber\": \"string\",\n"
                                         "      \"bankAddress\": {\n"
                                         "        \"name\": \"string\",\n"
                                         "        \"address\": \"string\"\n"
                                         "      },\n"
                                         "      \"beneficiaryBankBIC\": \"string\",\n"
                                         "      \"fedWireNumber\": \"string\",\n"
                                         "      \"sortCode\": \"string\",\n"
                                         "      \"chipNumber\": \"string\",\n"
                                         "      \"routingNumber\": \"string\",\n"
                                         "      \"legalEntityIdentifier\": \"string\"\n"
                                         "    }\n"
                                         "  }\n"
                                         "}\n"
                                         "";

const char *const BANKING_DOMESTIC_PAYEE = "{\n"
                                           "  \"payeeAccountUType\": \"account\",\n"
                                           "  \"account\": {\n"
                                           "    \"accountName\": \"string\",\n"
                                           "    \"bsb\": \"string\",\n"
                                           "    \"accountNumber\": \"string\"\n"
                                           "  },\n"
                                           "  \"card\": {\n"
                                           "    \"cardNumber\": \"string\"\n"
                                           "  },\n"
                                           "  \"payId\": {\n"
                                           "    \"name\": \"string\",\n"
                                           "    \"identifier\": \"string\",\n"
                                           "    \"type\": \"EMAIL\"\n"
                                           "  }\n"
                                           "}";

const char *const BANKING_DOMESTIC_PAYEE_ACCOUNT = "\n"
                                                   "\n"
                                                   "{\n"
                                                   "  \"accountName\": \"string\",\n"
                                                   "  \"bsb\": \"string\",\n"
                                                   "  \"accountNumber\": \"string\"\n"
                                                   "}";

const char *const BANKING_DOMESTIC_PAYEE_CARD = "{\n"
                                                "  \"cardNumber\": \"string\"\n"
                                                "}";

const char *const BANKING_DOMESTIC_PAYEE_PAY_ID = "{\n"
                                                  "  \"name\": \"string\",\n"
                                                  "  \"identifier\": \"string\",\n"
                                                  "  \"type\": \"EMAIL\"\n"
                                                  "}";

const char *const BANKING_BILLER_PAYEE = "{\n"
                                         "  \"billerCode\": \"string\",\n"
                                         "  \"crn\": \"string\",\n"
                                         "  \"billerName\": \"string\"\n"
                                         "}";

const char *const BANKING_INTERNATIONAL_PAYEE = "{\n"
                                                "  \"beneficiaryDetails\": {\n"
                                                "    \"name\": \"string\",\n"
                                                "    \"country\": \"string\",\n"
                                                "    \"message\": \"string\"\n"
                                                "  },\n"
                                                "  \"bankDetails\": {\n"
                                                "    \"country\": \"string\",\n"
                                                "    \"accountNumber\": \"string\",\n"
                                                "    \"bankAddress\": {\n"
                                                "      \"name\": \"string\",\n"
                                                "      \"address\": \"string\"\n"
                                                "    },\n"
                                                "    \"beneficiaryBankBIC\": \"string\",\n"
                                                "    \"fedWireNumber\": \"string\",\n"
                                                "    \"sortCode\": \"string\",\n"
                                                "    \"chipNumber\": \"string\",\n"
                                                "    \"routingNumber\": \"string\",\n"
                                                "    \"legalEntityIdentifier\": \"string\"\n"
                                                "  }\n"
                                                "}";

const char *const BANKING_DIRECT_DEBIT = "{\n"
                                         "  \"accountId\": \"string\",\n"
                                         "  \"authorisedEntity\": {\n"
                                         "    \"description\": \"string\",\n"
                                         "    \"financialInstitution\": \"string\",\n"
                                         "    \"abn\": \"string\",\n"
                                         "    \"acn\": \"string\",\n"
                                         "    \"arbn\": \"string\"\n"
                                         "  },\n"
                                         "  \"lastDebitDateTime\": \"string\",\n"
                                         "  \"lastDebitAmount\": \"string\"\n"
                                         "}";

const char *const BANKING_AUTHORISED_ENTITY = "{\n"
                                              "  \"description\": \"string\",\n"
                                              "  \"financialInstitution\": \"string\",\n"
                                              "  \"abn\": \"string\",\n"
                                              "  \"acn\": \"string\",\n"
                                              "  \"arbn\": \"string\"\n"
                                              "}";

const char *const BANKING_SCHEDULED_PAYMENT = "{\n"
                                              "  \"scheduledPaymentId\": \"string\",\n"
                                              "  \"nickname\": \"string\",\n"
                                              "  \"payerReference\": \"string\",\n"
                                              "  \"payeeReference\": \"string\",\n"
                                              "  \"status\": \"ACTIVE\",\n"
                                              "  \"from\": {\n"
                                              "    \"accountId\": \"string\"\n"
                                              "  },\n"
                                              "  \"paymentSet\": [\n"
                                              "    {\n"
                                              "      \"to\": {\n"
                                              "        \"toUType\": \"accountId\",\n"
                                              "        \"accountId\": \"string\",\n"
                                              "        \"payeeId\": \"string\",\n"
                                              "        \"domestic\": {\n"
                                              "          \"payeeAccountUType\": \"account\",\n"
                                              "          \"account\": {\n"
                                              "            \"accountName\": \"string\",\n"
                                              "            \"bsb\": \"string\",\n"
                                              "            \"accountNumber\": \"string\"\n"
                                              "          },\n"
                                              "          \"card\": {\n"
                                              "            \"cardNumber\": \"string\"\n"
                                              "          },\n"
                                              "          \"payId\": {\n"
                                              "            \"name\": \"string\",\n"
                                              "            \"identifier\": \"string\",\n"
                                              "            \"type\": \"EMAIL\"\n"
                                              "          }\n"
                                              "        },\n"
                                              "        \"biller\": {\n"
                                              "          \"billerCode\": \"string\",\n"
                                              "          \"crn\": \"string\",\n"
                                              "          \"billerName\": \"string\"\n"
                                              "        },\n"
                                              "        \"international\": {\n"
                                              "          \"beneficiaryDetails\": {\n"
                                              "            \"name\": \"string\",\n"
                                              "            \"country\": \"string\",\n"
                                              "            \"message\": \"string\"\n"
                                              "          },\n"
                                              "          \"bankDetails\": {\n"
                                              "            \"country\": \"string\",\n"
                                              "            \"accountNumber\": \"string\",\n"
                                              "            \"bankAddress\": {\n"
                                              "              \"name\": \"string\",\n"
                                              "              \"address\": \"string\"\n"
                                              "            },\n"
                                              "            \"beneficiaryBankBIC\": \"string\",\n"
                                              "            \"fedWireNumber\": \"string\",\n"
                                              "            \"sortCode\": \"string\",\n"
                                              "            \"chipNumber\": \"string\",\n"
                                              "            \"routingNumber\": \"string\",\n"
                                              "            \"legalEntityIdentifier\": \"string\"\n"
                                              "          }\n"
                                              "        }\n"
                                              "      },\n"
                                              "      \"isAmountCalculated\": true,\n"
                                              "      \"amount\": \"string\",\n"
                                              "      \"currency\": \"string\"\n"
                                              "    }\n"
                                              "  ],\n"
                                              "  \"recurrence\": {\n"
                                              "    \"nextPaymentDate\": \"string\",\n"
                                              "    \"recurrenceUType\": \"onceOff\",\n"
                                              "    \"onceOff\": {\n"
                                              "      \"paymentDate\": \"string\"\n"
                                              "    },\n"
                                              "    \"intervalSchedule\": {\n"
                                              "      \"finalPaymentDate\": \"string\",\n"
                                              "      \"paymentsRemaining\": 0,\n"
                                              "      \"nonBusinessDayTreatment\": \"ON\",\n"
                                              "      \"intervals\": [\n"
                                              "        {\n"
                                              "          \"interval\": \"string\",\n"
                                              "          \"dayInInterval\": \"string\"\n"
                                              "        }\n"
                                              "      ]\n"
                                              "    },\n"
                                              "    \"lastWeekDay\": {\n"
                                              "      \"finalPaymentDate\": \"string\",\n"
                                              "      \"paymentsRemaining\": 0,\n"
                                              "      \"interval\": \"string\",\n"
                                              "      \"lastWeekDay\": \"MON\",\n"
                                              "      \"nonBusinessDayTreatment\": \"ON\"\n"
                                              "    },\n"
                                              "    \"eventBased\": {\n"
                                              "      \"description\": \"string\"\n"
                                              "    }\n"
                                              "  }\n"
                                              "}";

const char *const BANKING_SCHEDULED_PAYMENT_SET = "{\n"
                                                  "  \"to\": {\n"
                                                  "    \"toUType\": \"accountId\",\n"
                                                  "    \"accountId\": \"string\",\n"
                                                  "    \"payeeId\": \"string\",\n"
                                                  "    \"domestic\": {\n"
                                                  "      \"payeeAccountUType\": \"account\",\n"
                                                  "      \"account\": {\n"
                                                  "        \"accountName\": \"string\",\n"
                                                  "        \"bsb\": \"string\",\n"
                                                  "        \"accountNumber\": \"string\"\n"
                                                  "      },\n"
                                                  "      \"card\": {\n"
                                                  "        \"cardNumber\": \"string\"\n"
                                                  "      },\n"
                                                  "      \"payId\": {\n"
                                                  "        \"name\": \"string\",\n"
                                                  "        \"identifier\": \"string\",\n"
                                                  "        \"type\": \"EMAIL\"\n"
                                                  "      }\n"
                                                  "    },\n"
                                                  "    \"biller\": {\n"
                                                  "      \"billerCode\": \"string\",\n"
                                                  "      \"crn\": \"string\",\n"
                                                  "      \"billerName\": \"string\"\n"
                                                  "    },\n"
                                                  "    \"international\": {\n"
                                                  "      \"beneficiaryDetails\": {\n"
                                                  "        \"name\": \"string\",\n"
                                                  "        \"country\": \"string\",\n"
                                                  "        \"message\": \"string\"\n"
                                                  "      },\n"
                                                  "      \"bankDetails\": {\n"
                                                  "        \"country\": \"string\",\n"
                                                  "        \"accountNumber\": \"string\",\n"
                                                  "        \"bankAddress\": {\n"
                                                  "          \"name\": \"string\",\n"
                                                  "          \"address\": \"string\"\n"
                                                  "        },\n"
                                                  "        \"beneficiaryBankBIC\": \"string\",\n"
                                                  "        \"fedWireNumber\": \"string\",\n"
                                                  "        \"sortCode\": \"string\",\n"
                                                  "        \"chipNumber\": \"string\",\n"
                                                  "        \"routingNumber\": \"string\",\n"
                                                  "        \"legalEntityIdentifier\": \"string\"\n"
                                                  "      }\n"
                                                  "    }\n"
                                                  "  },\n"
                                                  "  \"isAmountCalculated\": true,\n"
                                                  "  \"amount\": \"string\",\n"
                                                  "  \"currency\": \"string\"\n"
                                                  "}";

const char *const BANKING_SCHEDULED_PAYMENT_TO = "{\n"
                                                 "  \"toUType\": \"accountId\",\n"
                                                 "  \"accountId\": \"string\",\n"
                                                 "  \"payeeId\": \"string\",\n"
                                                 "  \"domestic\": {\n"
                                                 "    \"payeeAccountUType\": \"account\",\n"
                                                 "    \"account\": {\n"
                                                 "      \"accountName\": \"string\",\n"
                                                 "      \"bsb\": \"string\",\n"
                                                 "      \"accountNumber\": \"string\"\n"
                                                 "    },\n"
                                                 "    \"card\": {\n"
                                                 "      \"cardNumber\": \"string\"\n"
                                                 "    },\n"
                                                 "    \"payId\": {\n"
                                                 "      \"name\": \"string\",\n"
                                                 "      \"identifier\": \"string\",\n"
                                                 "      \"type\": \"EMAIL\"\n"
                                                 "    }\n"
                                                 "  },\n"
                                                 "  \"biller\": {\n"
                                                 "    \"billerCode\": \"string\",\n"
                                                 "    \"crn\": \"string\",\n"
                                                 "    \"billerName\": \"string\"\n"
                                                 "  },\n"
                                                 "  \"international\": {\n"
                                                 "    \"beneficiaryDetails\": {\n"
                                                 "      \"name\": \"string\",\n"
                                                 "      \"country\": \"string\",\n"
                                                 "      \"message\": \"string\"\n"
                                                 "    },\n"
                                                 "    \"bankDetails\": {\n"
                                                 "      \"country\": \"string\",\n"
                                                 "      \"accountNumber\": \"string\",\n"
                                                 "      \"bankAddress\": {\n"
                                                 "        \"name\": \"string\",\n"
                                                 "        \"address\": \"string\"\n"
                                                 "      },\n"
                                                 "      \"beneficiaryBankBIC\": \"string\",\n"
                                                 "      \"fedWireNumber\": \"string\",\n"
                                                 "      \"sortCode\": \"string\",\n"
                                                 "      \"chipNumber\": \"string\",\n"
                                                 "      \"routingNumber\": \"string\",\n"
                                                 "      \"legalEntityIdentifier\": \"string\"\n"
                                                 "    }\n"
                                                 "  }\n"
                                                 "}";

const char *const BANKING_SCHEDULED_PAYMENT_FROM = "{\n"
                                                   "  \"accountId\": \"string\"\n"
                                                   "}";

const char *const BANKING_SCHEDULED_PAYMENT_RECURRENCE = "{\n"
                                                         "  \"nextPaymentDate\": \"string\",\n"
                                                         "  \"recurrenceUType\": \"onceOff\",\n"
                                                         "  \"onceOff\": {\n"
                                                         "    \"paymentDate\": \"string\"\n"
                                                         "  },\n"
                                                         "  \"intervalSchedule\": {\n"
                                                         "    \"finalPaymentDate\": \"string\",\n"
                                                         "    \"paymentsRemaining\": 0,\n"
                                                         "    \"nonBusinessDayTreatment\": \"ON\",\n"
                                                         "    \"intervals\": [\n"
                                                         "      {\n"
                                                         "        \"interval\": \"string\",\n"
                                                         "        \"dayInInterval\": \"string\"\n"
                                                         "      }\n"
                                                         "    ]\n"
                                                         "  },\n"
                                                         "  \"lastWeekDay\": {\n"
                                                         "    \"finalPaymentDate\": \"string\",\n"
                                                         "    \"paymentsRemaining\": 0,\n"
                                                         "    \"interval\": \"string\",\n"
                                                         "    \"lastWeekDay\": \"MON\",\n"
                                                         "    \"nonBusinessDayTreatment\": \"ON\"\n"
                                                         "  },\n"
                                                         "  \"eventBased\": {\n"
                                                         "    \"description\": \"string\"\n"
                                                         "  }\n"
                                                         "}";

const char *const BANKING_SCHEDULED_PAYMENT_RECURRENCE_ONCE_OFF = "{\n"
                                                                  "  \"paymentDate\": \"string\"\n"
                                                                  "}";

const char *const BANKING_SCHEDULED_PAYMENT_RECURRENCE_INTERVAL_SCHEDULE = "{\n"
                                                                           "  \"finalPaymentDate\": \"string\",\n"
                                                                           "  \"paymentsRemaining\": 0,\n"
                                                                           "  \"nonBusinessDayTreatment\": \"ON\",\n"
                                                                           "  \"intervals\": [\n"
                                                                           "    {\n"
                                                                           "      \"interval\": \"string\",\n"
                                                                           "      \"dayInInterval\": \"string\"\n"
                                                                           "    }\n"
                                                                           "  ]\n"
                                                                           "}";

const char *const BANKING_SCHEDULED_PAYMENT_INTERVAL = "{\n"
                                                       "  \"interval\": \"string\",\n"
                                                       "  \"dayInInterval\": \"string\"\n"
                                                       "}";

const char *const BANKING_SCHEDULED_PAYMENT_RECURRENCE_LAST_WEEKDAY = "{\n"
                                                                      "  \"finalPaymentDate\": \"string\",\n"
                                                                      "  \"paymentsRemaining\": 0,\n"
                                                                      "  \"interval\": \"string\",\n"
                                                                      "  \"lastWeekDay\": \"MON\",\n"
                                                                      "  \"nonBusinessDayTreatment\": \"ON\"\n"
                                                                      "}";

const char *const BANKING_SCHEDULED_PAYMENT_RECURRENCE_EVENT_BASED = "{\n"
                                                                     "  \"description\": \"string\"\n"
                                                                     "}";

#endif //REGIME_V1_TEST_CONSTANTS_HPP
